#pragma once

#define TOUCAN_SCREEN_0 0
#define TOUCAN_SCREEN_1 1
#define TOUCAN_SCREEN_2 2
#define TOUCAN_SCREEN_3 3
#define TOUCAN_SCREEN_4 4
#define TOUCAN_SCREEN_5 5
#define TOUCAN_SCREEN_6 6
#define TOUCAN_SCREEN_COUNT 7
#define TOUCAN_SCREEN_NEXT 7
#define TOUCAN_SCREEN_PREV 8
